# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    working_directory: /var/www/html
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.4-apache

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/mariadb
        environment:
          MYSQL_ROOT_PASSWORD: my-secret-pw
          MYSQL_DATABASE: g_db
          MYSQL_USER: g_user
          MYSQL_PASSWORD: password

    steps:
      - checkout
      - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install mysqli
      - run: |
          echo 127.0.0.1 localhost | sudo tee -a /etc/hosts
          cat /etc/hosts

      - run: sudo service apache2 restart

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      # run tests with phpunit or codecept
      - run: ./vendor/bin/phpunit tests/phpunit/InstallSqlTest.php
      - run: ./vendor/bin/phpunit tests/phpunit/ConfigTest.php
      - run: ./vendor/bin/phpunit tests/phpunit/TableTest.php
      - run: ./vendor/bin/phpunit tests/phpunit/TableSchemaTest.php
      - run: ./vendor/bin/phpunit tests/phpunit/UserAgentTest.php
      - run: ./vendor/bin/phpunit tests/phpunit/ViewTest.php
      - run: ./vendor/bin/phpunit tests/phpunit/FileManagerTest.php
      - run: ./vendor/bin/phpunit tests/phpunit/RouterTest.php
      - run: ./vendor/bin/phpunit tests/phpunit/SlugifyTest.php
      - run: ./vendor/bin/phpunit tests/phpunit/CacheTest.php
      - run: ./vendor/bin/phpunit tests/phpunit/UserTest.php
      - run: ./vendor/bin/phpunit tests/phpunit/SessionTest.php
      - run: ./vendor/bin/phpunit tests/phpunit/RequestTest.php
      - run: ./vendor/bin/phpunit tests/phpunit/requests.php
