						<div class="contact_us">

							<h1>Contact us</h1>

							<p>Morbi accumsan ipsum velit. Nam nec tellus a odio tincidunt auctor a
							ornare odio. Sed non  mauris vitae erat consequat auctor eu in elit. Class
							aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos Sed non  mauris vitae erat consequat auctor eu in elit. Class
							aptent taciti sociosqu</p>

							<form>
								<p><input type="text" class="wpcf7-text" placeholder="Full Name*"/></p>
								<p><input type="text" class="wpcf7-email" placeholder="Email*"/></p>
								<p><input type="text" class="wpcf7-text" placeholder="Subject*"/></p>
								<p><textarea class="wpcf7-textarea" placeholder="Message*"></textarea></p>
								<p><input type="Submit" class="wpcf7-submit" value="Submit"/></p>
							</form>

						</div>

					</div>
