
						<div class="single_work_page clearfix">
							<div class="work_single_page_feature"><img src="themes/yellow-blog/images/slider-img.png"/></div>
							<div class="work_meta clearfix">
								<p class="floatleft">Completed : <span> 20 January 2014</span> Client Name: <span>John Smith</span></p>
								<a class="floatright" href="" target="_blank">Preview</a>
							</div>
							<div class="single_work_page_content">
								<p>Morbi accumsan ipsum velit. Nam nec tellus a odio tincidunt auctor a ornare odio.
								Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad
								litora torquent per conubia nostra, per inceptos Sed non mauris vitae erat consequat
								auctor eu in elit. Class aptent taciti sociosqu</p>
								<br/>
								<p>Morbi accumsan ipsum velit. Nam nec tellus a odio tincidunt auctor a ornare odio.
								Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad
								litora torquent per conubia nostra, per inceptos Sed non mauris vitae erat consequat
								auctor eu in elit. Class aptent taciti sociosqu</p>
								<br/>
								<p>Morbi accumsan ipsum velit. Nam nec tellus a odio tincidunt auctor a ornare odio.
								Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad
								litora torquent per conubia nostra, per inceptos Sed non mauris vitae erat consequat
								auctor eu in elit. Class aptent taciti sociosqu</p>
								<br/>
							</div>

						</div>
