
						<div class="clearfix single_work_container">
							<div class="clearfix single_work">
								<img class="img_top" src="themes/yellow-blog/images/work1.png" alt=""/>
								<img class="img_bottom" src="themes/yellow-blog/images/work_bg2.png" alt=""/>
								<h2>Lorem IpsumDolor Sit Amet</h2>
								<a href=""><p class="caption">Aenean sollicitudin, lorem quis bibendum auctor, nisi elit
									consequat ipsum, nec sagittis sem nibh id elit.</p></a>
							</div>
							<div class="clearfix single_work">
								<img src="themes/yellow-blog/images/work1.png" alt=""/>
								<h2>Lorem IpsumDolor Sit Amet</h2>
								<p>Aenean sollicitudin, lorem quis bibendum auctor, nisi elit
									consequat ipsum, nec sagittis sem nibh id elit.</p>
							</div>
							<div class="clearfix single_work">
								<img src="themes/yellow-blog/images/work1.png" alt=""/>
								<h2>Lorem IpsumDolor Sit Amet</h2>
								<p>Aenean sollicitudin, lorem quis bibendum auctor, nisi elit
									consequat ipsum, nec sagittis sem nibh id elit.</p>
							</div>
							<div class="clearfix single_work">
								<img src="themes/yellow-blog/images/work1.png" alt=""/>
								<h2>Lorem IpsumDolor Sit Amet</h2>
								<p>Aenean sollicitudin, lorem quis bibendum auctor, nisi elit
									consequat ipsum, nec sagittis sem nibh id elit.</p>
							</div>

							<div class="clearfix work_pagination">
								<nav>
									<a class="newer floatleft" href=""> < -- Newer Post</a>
									<a class="older floatright" href="">Older Post -- ></a>
								</nav>
							</div>
						</div>
