<?php global $posts,$pages,$users,$packages; ?>
<div class='row'>
  <div class='gm-3 wrapper'>
    <a href="admin/posts">
        <div class='alert success'><h3><?=$posts?> Posts</h3></div>
    </a>
  </div>
  <div class='gm-3 wrapper'>
    <a href="admin/users">
        <div class='alert primary'><h3><?=$users?> Users</h3></div>
    </a>
  </div>
  <div class='gm-3 wrapper'>
    <a href="admin/pages">
        <div class='alert warning'><h3><?=$pages?> Pages</h3></div>
    </a>
  </div>
  <div class='gm-3 wrapper'>
    <a href="admin/addons">
        <div class='alert'><h3><?=$packages?> Packages</h3></div>
    </a>
  </div>
</div>
