<?php global $posts,$pages,$users,$packages; ?>
<div class='row'>
  <div class='gm-3 wrapper'>
    <div class='alert success'><h3><?=$posts?> Posts</h3></div>
  </div>
  <div class='gm-3 wrapper'>
    <div class='alert primary'><h3><?=$users?> Users</h3></div>
  </div>
  <div class='gm-3 wrapper'>
    <div class='alert warning'><h3><?=$pages?> Pages</h3></div>
  </div>
  <div class='gm-3 wrapper'>
    <div class='alert'><h3><?=$packages?> Packages</h3></div>
  </div>
</div>
