
<?php
global $db;
$p_list = ['title', 'post', 'publish' ];
if ($_SERVER['REQUEST_METHOD'] === 'POST') if (router::post('submit-btn')=='submited'){
    $title = $_POST['p_title'];
    $text = $_POST['p_post'];
    $img = trim($_POST['p_img']);
    $tags = $_POST['p_tags'];
    $categories = isset($_POST['p_categories'])?$_POST['p_categories']:[];
    $publish = isset($_POST['p_publish'])?1:0;
    $slugify = new Cocur\Slugify\Slugify();
    $slug = $slugify->slugify($title);
    $args = [$title,$text,$publish,$slug];
    if ($id == "new") {
        $db->query("INSERT INTO post(title,post,publish,slug) VALUES(?,?,?,?)",$args);
        $id = $db->insert_id;
    }
    else {
        $db->query("UPDATE post SET title=?,post=?,publish=?,slug=? WHERE id=$id",$args);
    }

    $db->query("DELETE FROM postmeta WHERE post_id=? AND vartype IN('category','tag','thumbnail')",$id);
    if($img!='') $db->query("INSERT INTO postmeta(post_id,vartype,value) VALUES(?,'thumbnail',?);",[$id,$img]);
    if($categories) foreach($categories as $c)
        $db->query("INSERT INTO postmeta(post_id,vartype,value) VALUES(?,'category',?);",[$id,$c]);
    if($tags) foreach(explode(',',$tags) as $t) {
        $t = trim($t);
        if($t!='') $db->query("INSERT INTO postmeta(post_id,vartype,value) VALUES(?,'tag',?);",[$id,$t]);
    }

    echo "<div class='alert success'>Changes have been saved successfully!</div>";
}

if ($id == 'new') {
    $p = (object)['tags'=>'','img'=>'','title'=>'','post'=>'','publish'=>1,'id'=>(isset($_POST['p_id'])?$_POST['p_id']:0)];
}
else {
    $ql="SELECT id,title,post,publish,
        (SELECT a.value FROM postmeta a WHERE a.post_id=post.id AND vartype='thumbnail') as img,
        (SELECT GROUP_CONCAT(b.value SEPARATOR ', ') FROM postmeta b WHERE b.post_id=post.id AND vartype='tag') as tags
        FROM post WHERE id=$id";
    $res = $db->query($ql);
    if ($res) $p=mysqli_fetch_object($res); else die("The post '$id' could not be found in db!");

    $ql="SELECT id,title FROM postcategory";
    $categories = $db->get($ql);
    $ql="SELECT value FROM postmeta WHERE vartype='category' AND post_id=$id";
    $selectedcategories = $db->getList($ql);
}

?>

<div class="row ">
<form id="postForm" method="post" class="g-form" action="admin/posts/<?=($p->id?:'new')?>">
    <input value="<?=($p->id?:'new')?>" name="p_id" type="hidden"/>

    <div class="row ">
        <label class="gm-2">Title</label>
        <input class="gm-10" value="<?=$p->title?>" name="p_title"/>
    </div>

    <div class="row ">
        <label class="gm-2">Thumbnail</label>
        <div class="gm-10 g-group">
          <span class="btn g-group-item" style="width:28px" onclick="open_gallery()"><i class="fa fa-image"></i></span>
          <span class="g-group-item"><input class="fullwidth" value="<?=$p->img?>" name="p_img"/><span>
        </div>
    </div>

    <div class="row ">
        <label class="gm-2">Categories</label>
        <select class="select2" multiple class="gm-10 gm-10" style="width:83.333%" name="p_categories[]">
            <?php foreach ($categories as $key => $value) {
                echo '<option value="'.$value[0].'"'.(in_array($value[0],$selectedcategories)?' selected':'').'>'.$value[1].'</option>';
            } ?>
        </select>
    </div>
    <div class="row ">
        <label class="gm-2">Tags</label>
        <input class="gm-10" placeholder="values seperated by comma" name="p_tags" value="<?=$p->tags?>"/>
    </div>

    <div class="row ">
        <label class="gm-2" for="p_publish">Public</label>
        <label class="g-switch"  for="p_publish">
            <input type="checkbox" id="p_publish" name="p_publish" <?=($p->publish==1?' checked':'')?>>
            <div class="g-slider"></div>
        </label>
        <!--label class="col-md-3">Public<input type="checkbox" name="p_publish" value="1"></label-->
    </div>
    <hr>

    <div class="row">
        <div id="quill-toolbar-container">
            <span class="ql-formats">
               <select class="ql-font"></select>
               <select class="ql-size"></select>
             </span>
             <span class="ql-formats">
               <button class="ql-bold"></button>
               <button class="ql-italic"></button>
               <button class="ql-underline"></button>
               <button class="ql-strike"></button>
             </span>
             <span class="ql-formats">
               <select class="ql-color"></select>
               <select class="ql-background"></select>
             </span>
             <span class="ql-formats">
               <button class="ql-script" value="sub"></button>
               <button class="ql-script" value="super"></button>
             </span>
             <span class="ql-formats">
               <button class="ql-header" value="1"></button>
               <button class="ql-header" value="2"></button>
               <button class="ql-blockquote"></button>
               <button class="ql-code-block"></button>
             </span>
             <span class="ql-formats">
               <button class="ql-list" value="ordered"></button>
               <button class="ql-list" value="bullet"></button>
               <button class="ql-indent" value="-1"></button>
               <button class="ql-indent" value="+1"></button>
             </span>
             <span class="ql-formats">
               <button class="ql-direction" value="rtl"></button>
               <select class="ql-align"></select>
             </span>
             <span class="ql-formats">
               <button class="ql-link"></button>
               <button class="ql-add-image" onclick="if(quill.getSelection()) open_gallery_post()"><i class="fa fa-image"></i></button>
               <button class="ql-video"></button>
               <!--button class="ql-formula"></button-->
             </span>
             <span class="ql-formats">
               <button class="ql-clean"></button>
             </span>
        </div>
        <input type="hidden" name="p_post" id="p_post">
        <input type="hidden" name="submit-btn" id="submit-btn">
        <div id="quill-container" style="width:100%;background:white;height:350px"><?=nl2br($p->post)?></div>
    </div>

    <div class="row wrapper">
        <div class="btn-group">
            <button onclick="g('#p_post').attr('value',g('#quill-container .ql-editor').all[0].innerHTML);g.el('submit-btn').value='submited'; submit()" class="btn btn-primary primary" >Submit</button>
        </div>
    </div>
</form>
</div>

<!--script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0/katex.min.js"></script>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.3.0/highlight.min.js"></script-->
<link rel="stylesheet" href="lib/quill/quill.snow.css" />
<script type="text/javascript" src="lib/quill/quill.min.js"></script>

<script type="text/javascript">
  var quill = new Quill('#quill-container', {
    modules: {
      //formula: true,
      //syntax: true,
      toolbar: '#quill-toolbar-container'
    },
    placeholder: 'Compose an epic...',
    theme: 'snow'
  });
</script>

<!--script src="lib/tinymce/js/tinymce/tinymce.min.js"></script-->
<script>
//cdn.tinymce.com/4/tinymce.min.js
//tinymce.init({ selector:'textarea' });
/*
tinymce.init({
  selector: '[name=p_post]',
  mode: 'none',
  height: 300,
  //theme: 'modern',
  plugins: [
    'advlist autolink lists link image charmap print  hr anchor pagebreak',
    'searchreplace wordcount  visualchars code ',
    'insertdatetime media nonbreaking table contextmenu ', //directionality fullscreen visualblocks preview
    'template paste textcolor colorpicker textpattern imagetools codesample toc' //example_dependency emoticons
],
  toolbar1: 'styleselect | forecolor backcolor bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link media image codesample',
  //theme_advanced_buttons3_add : "visualchars",
  //toolbar2: 'print preview  |   emoticons | table',
  //image_advtab: true,
  templates: <?php echo json_encode((isset($templates)?$templates:[])); ?>,
  document_base_url : "//localhost/gila/",
  content_css: <?php echo json_encode(isset($content_css)?$content_css:[]); ?>
 });
*/
if(typeof requiredRes=='undefined') requiredRes = {}

g.require('lib/jquery/jquery-2.2.4.min.js',function(){
    g.loadCSS('lib/select2/select2.min.css');
    g.require(['lib/select2/select2.min.js'],function(){
        $('.select2').select2();
    })
})

g.dialog.buttons.select_path = {
    title:'Select',fn:function(){
        let v = g('#selected-path').attr('value')
        if(v!=null) g('[name=p_img]').attr('value',v)
        g('#gila-darkscreen').remove();
    }
}
g.dialog.buttons.select_path_post = {
    title:'Select',fn:function(){
        if(!quill.getSelection()) return
        index=quill.getSelection().index
        let v = g('#selected-path').attr('value')
        if(v!=null) quill.insertEmbed(index, 'image', v);
        g('#gila-darkscreen').remove();
    }
}
g.click(".gal-image",function(){
    g('.gal-path').removeClass('g-selected');
    g(this).addClass('g-selected');
    g('#selected-path').attr('value',this.getAttribute('data-path'))
})
g.click(".gal-folder",function(){
    let path=this.getAttribute('data-path')
    g.ajax({url:"admin/media",method:"POST",header:"application/x-www-form-urlencoded",data:"path="+path,fn:function(gal){ //
        g('#gila-popup>.body').html(gal)
    }})
})
g.click("#fm-goup",function(){
    if(this.getAttribute('data-path')=='') return;

    let path=this.getAttribute('data-path')
    g.post("admin/media","path="+path,function(gal){ //
        g('#gila-popup>.body').html(gal)
    })
})

function gallery_upload_files() {
    let fm=new FormData() //g.el('upload_files_form')
    fm.append('uploadfiles', g.el('upload_files').files[0]);
    fm.append('path', g.el('upload_files').getAttribute('data-path'));
    g.ajax({url:"admin/media_upload",method:'POST',data:fm, fn: function (gal){
        g('#gila-popup>.body').html(gal)
    }})
    /*g.upload("admin/media_upload",fm,function(gal){
        g('#gila-popup>.body').html(gal)
    })*/
}

function open_gallery() {
    g.post("admin/media","path=assets",function(gal){ //
        g.dialog({title:"Gila gallery",body:gal,buttons:'select_path'})
    })
}
function open_gallery_post() {
    g.post("admin/media","path=assets",function(gal){ //
        g.dialog({title:"Gila gallery",body:gal,buttons:'select_path_post'})
    })
}
</script>
