
<?php
global $db;
$p_list = ['title', 'post', 'publish' ];
if ($_SERVER['REQUEST_METHOD'] === 'POST') if ($_POST['submit-btn']=='submited'){
    $title = $_POST['p_title'];
    $text = $_POST['p_post'];
    $img = trim($_POST['p_img']);
    $tags = $_POST['p_tags'];
    $categories = isset($_POST['p_categories'])?$_POST['p_categories']:[];
    $publish = isset($_POST['p_publish'])?1:0;
    $slugify = new Cocur\Slugify\Slugify();
    $slug = $slugify->slugify($title);
    $args = [$title,$text,$publish,$slug];
    if ($id == "new") {
        $db->query("INSERT INTO post(title,post,publish,slug) VALUES(?,?,?,?)",$args);
        $id = $db->insert_id;
    }
    else {
        $db->query("UPDATE post SET title=?,post=?,publish=?,slug=? WHERE id=$id",$args);
    }

    $db->query("DELETE FROM postmeta WHERE $id=? AND vartype IN('category','tag','thumbnail')",$id);
    if($img!='') $db->query("INSERT INTO postmeta(post_id,vartype,value) VALUES(?,'thumbnail',?);",[$id,$img]);
    if($categories) foreach($categories as $c)
        $db->query("INSERT INTO postmeta(post_id,vartype,value) VALUES(?,'category',?);",[$id,$c]);
    if($tags) foreach(explode(',',$tags) as $t) {
        $t = trim($t);
        if($t!='') $db->query("INSERT INTO postmeta(post_id,vartype,value) VALUES(?,'tag',?);",[$id,$t]);
    }

    echo "<div class='alert success'>Changes have been saved successfully!</div>";
}

if ($id == 'new') {
    $p = (object)['tags'=>'','img'=>'','title'=>'','post'=>'','publish'=>1,'id'=>(isset($_POST['p_id'])?$_POST['p_id']:0)];
}
else {
    $ql="SELECT id,title,post,publish,
        (SELECT a.value FROM postmeta a WHERE a.post_id=post.id AND vartype='thumbnail') as img,
        (SELECT GROUP_CONCAT(b.value SEPARATOR ', ') FROM postmeta b WHERE b.post_id=post.id AND vartype='tag') as tags
        FROM post WHERE id=$id";
    $res = $db->query($ql);
    if ($res) $p=mysqli_fetch_object($res); else die("The post '$id' could not be found in db!");

    $ql="SELECT id,title FROM postcategory";
    $categories = $db->get($ql);
    $ql="SELECT value FROM postmeta WHERE vartype='category' AND post_id=$id";
    $selectedcategories = $db->getList($ql);
}

?>

<div class="row ">
<form id="postForm" method="post" class="g-form" action="admin/posts/<?=($p->id?:'new')?>">
    <input value="<?=($p->id?:'new')?>" name="p_id" type="hidden"/>

    <div class="row ">
        <label class="gm-2">Title</label>
        <input class="gm-10" value="<?=$p->title?>" name="p_title"/>
    </div>

    <div class="row ">
        <label class="gm-2">Thumbnail</label>
        <input class="gm-10" value="<?=$p->img?>" name="p_img"/>
    </div>

    <div class="row ">
        <label class="gm-2">Categories</label>
        <select class="select2" multiple class="gm-10 gm-10" style="width:83.333%" name="p_categories[]">
            <?php foreach ($categories as $key => $value) {
                echo '<option value="'.$value[0].'"'.(in_array($value[0],$selectedcategories)?' selected':'').'>'.$value[1].'</option>';
            } ?>
        </select>
    </div>
    <div class="row ">
        <label class="gm-2">Tags</label>
        <input class="gm-10" placeholder="values seperated by comma" name="p_tags" value="<?=$p->tags?>"/>
    </div>

    <div class="row ">
        <label class="gm-2" for="p_publish">Public</label>
        <label class="g-switch"  for="p_publish">
            <input type="checkbox" id="p_publish" name="p_publish" <?=($p->publish==1?' checked':'')?>>
            <div class="g-slider"></div>
        </label>
        <!--label class="col-md-3">Public<input type="checkbox" name="p_publish" value="1"></label-->
    </div>
    <hr>

    <div class="row wrapper">
        <textarea name="p_post"><?=$p->post?></textarea>
    </div>

    <div class="row wrapper">
        <div class="btn-group">
            <input type="submit" name="submit-btn" class="btn btn-primary primary" onclick="this.value='submited'" />
        </div>
    </div>
</form>
</div>

<script src="libs/tinymce/js/tinymce/tinymce.min.js"></script>
<script>
//cdn.tinymce.com/4/tinymce.min.js
//tinymce.init({ selector:'textarea' });
tinymce.init({
  selector: '[name=p_post]',
  mode: 'none',
  height: 300,
  //theme: 'modern',
  plugins: [
    'advlist autolink lists link image charmap print  hr anchor pagebreak',
    'searchreplace wordcount  visualchars code ',
    'insertdatetime media nonbreaking table contextmenu ', //directionality fullscreen visualblocks preview
    'template paste textcolor colorpicker textpattern imagetools codesample toc' //example_dependency emoticons
],
  toolbar1: 'styleselect | forecolor backcolor bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link media image codesample',
  //theme_advanced_buttons3_add : "visualchars",
  //toolbar2: 'print preview  |   emoticons | table',
  //image_advtab: true,
  templates: <?php echo json_encode((isset($templates)?$templates:[])); ?>,
  document_base_url : "//localhost/gila/",
  content_css: <?php echo json_encode(isset($content_css)?$content_css:[]); ?>
 });

if(typeof requiredRes=='undefined') requiredRes = {}

g.require('libs/jquery/jquery-2.2.4.min.js',function(){
    g.loadCSS('libs/select2/select2.min.css');
    g.require(['libs/select2/select2.min.js'],function(){
        $('.select2').select2();
    })
})
</script>
