
<?php
global $db;
$p_list = ['title', 'page', 'publish' ];
if ($_SERVER['REQUEST_METHOD'] === 'POST') if (router::post('submit-btn')=='submited'){
    $title = $_POST['p_title'];
    $text = $_POST['p_page'];
    $publish = isset($_POST['p_publish'])?1:0;
    $slugify = new Cocur\Slugify\Slugify();
    $slug = $slugify->slugify($title);
    $args = [$title,$text,$publish,$slug];
    if ($id == "new") {
		$db->query("INSERT INTO page(title,page,publish,slug) VALUES(?,?,?,?)",$args);
        $id = $db->insert_id;
    }
    else {
        $db->query("UPDATE page SET title=?,page=?,publish=?,slug=? WHERE id=$id",$args);
    }

    echo "<div class='alert success'>Changes have been saved successfully!</div>";
}

if ($id == 'new') {
    $p = (object)['title'=>'','page'=>'','publish'=>1,'id'=>(isset($_POST['p_id'])?$_POST['p_id']:0)];
}
else {
    $ql="SELECT id,title,page,publish
        FROM page WHERE id=$id";
    $res = $db->query($ql);
    if ($res) $p=mysqli_fetch_object($res); else die("The page '$id' could not be found in db!");
}

?>

<div class="row ">
<form id="postForm" method="post" class="g-form" action="admin/pages/<?=($p->id?:'new')?>">
    <input value="<?=($p->id?:'new')?>" name="p_id" type="hidden"/>

    <div class="row ">
        <label class="gm-2">Title</label>
        <input class="gm-10" value="<?=$p->title?>" name="p_title"/>
    </div>

    <div class="row ">
        <label class="gm-2" for="p_publish">Public</label>
        <label class="g-switch"  for="p_publish">
            <input type="checkbox" id="p_publish" name="p_publish" <?=($p->publish==1?' checked':'')?>>
            <div class="g-slider"></div>
        </label>
        <!--label class="col-md-3">Public<input type="checkbox" name="p_publish" value="1"></label-->
    </div>
    <hr>

    <div class="row ">
        <div id="quill-toolbar-container">
            <span class="ql-formats">
               <select class="ql-font"></select>
               <select class="ql-size"></select>
             </span>
             <span class="ql-formats">
               <button class="ql-bold"></button>
               <button class="ql-italic"></button>
               <button class="ql-underline"></button>
               <button class="ql-strike"></button>
             </span>
             <span class="ql-formats">
               <select class="ql-color"></select>
               <select class="ql-background"></select>
             </span>
             <span class="ql-formats">
               <button class="ql-script" value="sub"></button>
               <button class="ql-script" value="super"></button>
             </span>
             <span class="ql-formats">
               <button class="ql-header" value="1"></button>
               <button class="ql-header" value="2"></button>
               <button class="ql-blockquote"></button>
               <button class="ql-code-block"></button>
             </span>
             <span class="ql-formats">
               <button class="ql-list" value="ordered"></button>
               <button class="ql-list" value="bullet"></button>
               <button class="ql-indent" value="-1"></button>
               <button class="ql-indent" value="+1"></button>
             </span>
             <span class="ql-formats">
               <button class="ql-direction" value="rtl"></button>
               <select class="ql-align"></select>
             </span>
             <span class="ql-formats">
               <button class="ql-link"></button>
               <button class="ql-image"></button>
               <button class="ql-video"></button>
               <!--button class="ql-formula"></button-->
             </span>
             <span class="ql-formats">
               <button class="ql-clean"></button>
             </span>
        </div>
        <div name="p_post" id="quill-container" style="width:100%;background:white;height:350px"><?=nl2br($p->page)?></div>
    </div>

    <div class="row wrapper">
        <div class="btn-group">
            <input type="submit" name="submit-btn" class="btn btn-primary primary" onclick="this.value='submited'" />
        </div>
    </div>
</form>
</div>

<!--script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0/katex.min.js"></script>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.3.0/highlight.min.js"></script-->
<link rel="stylesheet" href="lib/quill/quill.snow.css" />
<script type="text/javascript" src="lib/quill/quill.min.js"></script>

<script type="text/javascript">
  var quill = new Quill('#quill-container', {
    modules: {
      //formula: true,
      //syntax: true,
      toolbar: '#quill-toolbar-container'
    },
    placeholder: 'Compose an epic...',
    theme: 'snow'
  });
</script>
