
<?php
global $db;
$p_list = ['title', 'page', 'publish' ];
if ($_SERVER['REQUEST_METHOD'] === 'POST') if ($_POST['submit-btn']=='submited'){
    $title = $_POST['p_title'];
    $text = $_POST['p_page'];
    $publish = isset($_POST['p_publish'])?1:0;
    $slugify = new Cocur\Slugify\Slugify();
    $slug = $slugify->slugify($title);
    $args = [$title,$text,$publish,$slug];
    if ($id == "new") {
		echo "INSERT INTO page(title,`page`,publish,slug) VALUES('$title','$text','$publish',$slug)";
        $db->query("INSERT INTO page(title,page,publish,slug) VALUES(?,?,?,?)",$args);
        $id = $db->insert_id;
    }
    else {
        $db->query("UPDATE page SET title=?,page=?,publish=?,slug=? WHERE id=$id",$args);
    }

    echo "<div class='alert success'>Changes have been saved successfully!</div>";
}

if ($id == 'new') {
    $p = (object)['title'=>'','page'=>'','publish'=>1,'id'=>(isset($_POST['p_id'])?$_POST['p_id']:0)];
}
else {
    $ql="SELECT id,title,page,publish
        FROM page WHERE id=$id";
    $res = $db->query($ql);
    if ($res) $p=mysqli_fetch_object($res); else die("The page '$id' could not be found in db!");
}

?>

<div class="row ">
<form id="postForm" method="post" class="g-form" action="admin/pages/<?=($p->id?:'new')?>">
    <input value="<?=($p->id?:'new')?>" name="p_id" type="hidden"/>

    <div class="row ">
        <label class="gm-2">Title</label>
        <input class="gm-10" value="<?=$p->title?>" name="p_title"/>
    </div>

    <div class="row ">
        <label class="gm-2" for="p_publish">Public</label>
        <label class="g-switch"  for="p_publish">
            <input type="checkbox" id="p_publish" name="p_publish" <?=($p->publish==1?' checked':'')?>>
            <div class="g-slider"></div>
        </label>
        <!--label class="col-md-3">Public<input type="checkbox" name="p_publish" value="1"></label-->
    </div>
    <hr>

    <div class="row wrapper">
        <textarea name="p_page"><?=$p->page?></textarea>
    </div>

    <div class="row wrapper">
        <div class="btn-group">
            <input type="submit" name="submit-btn" class="btn btn-primary primary" onclick="this.value='submited'" />
        </div>
    </div>
</form>
</div>

<script src="libs/tinymce/js/tinymce/tinymce.min.js"></script>
<script>
//cdn.tinymce.com/4/tinymce.min.js
//tinymce.init({ selector:'textarea' });
tinymce.init({
  selector: '[name=p_page]',
  mode: 'none',
  height: 300,
  //theme: 'modern',
  plugins: [
    'advlist autolink lists link image charmap print  hr anchor pagebreak',
    'searchreplace wordcount  visualchars code ',
    'insertdatetime media nonbreaking table contextmenu ', //directionality fullscreen visualblocks preview
    'template paste textcolor colorpicker textpattern imagetools codesample toc' //example_dependency emoticons
],
  toolbar1: 'styleselect | forecolor backcolor bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link media image codesample',
  //theme_advanced_buttons3_add : "visualchars",
  //toolbar2: 'print preview  |   emoticons | table',
  //image_advtab: true,
  templates: <?php echo json_encode((isset($templates)?$templates:[])); ?>,
  document_base_url : "//localhost/gila/",
  content_css: <?php echo json_encode(isset($content_css)?$content_css:[]); ?>
 });


</script>
