<hr>
<div class="gm-12">
<label class="gm-4">Widget Area</label>
<select id="widget_area" value="<?=gila::config('default-controller')?>" class="gm-6 g-input">
<?php
foreach (gila::$widget_area as $value) {
    $sel = ($widget->area==$value?'selected':'');
    echo '<option value="'.$value."\" $sel>".ucwords($value).'</option>';
}
?>
</select>
<input type="hidden" value="<?=$widget->id?>" id='widget_id'>
