<link rel="stylesheet" type="text/css" href="lib/pnk/pnk.css?">
<div class='pnk-table' pnk-src='src/core/tables/widget' id='twidget'></div>

<script src='lib\jquery\jquery-2.2.4.min.js'></script>
<script src='lib\pnk\pnk-1.3.js?v=4'></script>

<script src="lib/CodeMirror/codemirror.js"></script>
<link rel="stylesheet" href="lib/CodeMirror/codemirror.css">
<script src="lib/CodeMirror/javascript.js"></script>

<script>

pnk_populate_tables(document);
/*
var textareas = document.getElementsByTagName('textarea');
var count = textareas.length;
for(var i=0;i<count;i++){
    textareas[i].onkeydown = function(e){
        if(e.keyCode==9 || e.which==9){
            e.preventDefault();
            var s = this.selectionStart;
            this.value = this.value.substring(0,this.selectionStart) + "\t" + this.value.substring(this.selectionEnd);
            this.selectionEnd = s+1;
        }
    }
}*/
</script>
<?php
return; ?>
<table class="table"><tr><th>ID<th>Widget<th>Area<th>Position<th>
<?php
  global $db;
        $gen = $db->gen("SELECT * FROM widget");
        foreach ($gen as $r) {
            echo '<tr>'.'<td>'.$r['id'].'<td>'.$r['widget'].'<td>'.$r['area'].'<td>'.$r['pos'].'<td>';
            echo '<a class="open-dialog" hr="admin/widgets/'.$r['id'].'">Edit</a>';
        }
?>
</table>

<script>
function widget_data_serialize () {
  return 'gggh';
}
g.dialog.buttons.update_widget = {title:'Update',fn:function(){
    widget_data = widget_data_serialize()
    widget_id = document.getElementById('widget_id').value
    widget_area = document.getElementById('widget_area').value
    $.post(
        "admin/update_widget",
        {widget_data:widget_data, widget_id:widget_id, widget_area:widget_area},
        function (response) {
            g('#gila-darkscreen').remove();
        }
    );
}};
g.dialog.buttons.close_widget = {title:'Cancel',fn:function(){
    g('#gila-darkscreen').remove();
}};

g.click(".open-dialog",function(){
  href=event.target.getAttribute('hr');
  g.ajax(href,function(data){
    g.dialog({class:'lightscreen',title:'title',body:data,buttons:'update_widget close_widget'})
    g.require('<?=gila::config('base')?>lib/jquery/jquery-sortable.js',function(){
      g.require('<?=gila::config('base')?>src/core/widgets/menu/edit.js');
    });
  });
  requiredRes = []


  return false;
})
</script>
