<?php
$config_list = ['title'=>'Title', 'slogan'=>'Slogan', 'base'=>'Website URL', 'ssl'=>'SSL URL' ];
if ($_SERVER['REQUEST_METHOD'] === 'POST') if ($_POST['submit-btn']=='submited'){
    foreach ($config_list as $key => $value) $GLOBALS['config'][$key] = $_POST['gila_'.$key];
    $GLOBALS['config']['theme'] = $_POST['gila_theme'];
    $GLOBALS['config']['default-controller'] = $_POST['gila_dc'];
    $GLOBALS['config']['timezone'] = $_POST['gila_timezone'];

    $filedata = "<?php\n\n\$GLOBALS['config'] = ".var_export($GLOBALS['config'], true).";";
    file_put_contents('config.php', $filedata);
    echo "<div class='alert success'>Changes have been saved successfully!</div>";
}
?>

<div class="col-md-12">
    <form method="post" action="admin/settings">

<?php

foreach ($config_list as $key=>$value) if($value[0] != '.') { ?>
    <br><div class="col-md-12">
    <label class="col-md-2 col-md-offset-1"><?=$value?></label>
    <input name="gila_<?=$key?>" value="<?=gila::config($key)?>" class="col-md-4" />
    </div>
<?php } ?>


    <br><div class="col-md-12">
    <label class="col-md-2 col-md-offset-1">Theme</label>
    <select name="gila_theme" value="<?=gila::config('theme')?>" class="col-md-3">
    <?php
    $theme_list=scandir('themes/');
    foreach ($theme_list as $value) if($value[0] != '.') {
        $sel = (gila::config('theme')==$value?'selected':'');
        echo '<option value="'.$value."\" $sel>".ucwords($value).'</option>';
    }
    ?>
    </select>
    </div>

    <br><div class="col-md-12">
        <label class="col-md-2 col-md-offset-1">Timezone</label>
        <select name="gila_timezone" value="<?=gila::config('timezone')?>" class="col-md-3">
        <?php
        foreach (DateTimeZone::listIdentifiers() as $value) {
            $sel = (gila::config('timezone')==$value?'selected':'');
            echo '<option value="'.$value."\" $sel>".ucwords($value).'</option>';
        }
        ?>
        </select>
    </div>

    <br><div class="col-md-12">
    <label class="col-md-2 col-md-offset-1">Default Controller</label>
    <select name="gila_dc" value="<?=gila::config('default-controller')?>" class="col-md-3">
    <?php
    foreach (gila::$controller as $k=>$value) if($value[0] != '.') {
        $sel = (gila::config('default-controller')==$k?'selected':'');
        echo '<option value="'.$k."\" $sel>".ucwords($k).'</option>';
    }
    ?>
    </select>
    </div>

    <br><input type="submit" name="submit-btn" onclick="this.value='submited'" class="btn btn-primary col-md-1 col-md-offset-1"  />
    </form>
</div>
