<link rel="stylesheet" type="text/css" href="lib/pnk/pnk.css?">
<link rel="stylesheet" type="text/css" href="lib/select2/select2.min.css">
<div class='pnk-table' pnk-src='src/core/tables/user' id='tuser'></div>

<?=view::script('lib\jquery\jquery-3.3.1.min.js')?>
<?=view::script('lib\pnk\pnk-1.3.js')?>
<?=view::script('lib\select2\select2.min.js')?>
<script>
pnk_populate_tables(document);
</script>
