<link rel="stylesheet" type="text/css" href="lib/pnk/pnk.css?">
<link rel="stylesheet" type="text/css" href="lib/select2/select2.min.css">
<div class='pnk-table' pnk-src='src/core/tables/user' id='tuser'></div>

<script src='lib\jquery\jquery-2.2.4.min.js'></script>
<script src='lib\pnk\pnk-1.3.js?v=4'></script>
<script src='lib\pnk\pnk-1.3.js?v=4'></script>
<script src='lib\select2\select2.min.js'></script>
<script>
pnk_populate_tables(document);
</script>
