
<head>
	<link type="text/css" rel="stylesheet" href="../libs/rj.css"/>
	<script src="../libs/rj.js"></script>
</head>
<!--div class="col-5"></div-->
<div class="col-6 display-flex margin-auto align-items-center " style="height:100%">
<form method='post' class="col-12 border box-shadow">
	<div class="col-6">
	<label>Hostname</label>
	<input name="db_host" value="localhost"/>
	<label>Database</label>
	<input name="db_name"/>
	<label>DB Username</label>
	<input name="db_user"/>
	<label>DB Password</label>
	<input name="db_pass" type="password"/>
	</div>
	<div class="col-6">
	<label>Admin Username</label>
	<input name="adm_user"/>
	<label>Admin Email</label>
	<input name="adm_email" type="email"/>
	<label>Admin Password</label>
	<input name="adm_pass" type="password"/>
	<label>Admin Password</label>
	<input name="adm_pass" type="password"/>
	</div>
	<div class="col-12"><input class="btn" type="submit"/></div>
</form>
</div>
