<div class="col-md-2"></div>
<div class="col-md-8">
    <textarea class="col-md-12"></textarea>
</div>
<div class="col-md-2">
    <a class="btn btn-primary" onclick="update_widget()">Update</a>
</div>

<script>

function update_widget() {
	var data = $('#widget_text').html();

    $.post(
        "admin/update_widget",
        {widget_data:data, widget_id:<?=$widget_id?>},
        function (response) {
            alert(response);
        }
    );
}

</script>
