<?php

return [
  'Gila\\Cache'=> 'src/core/classes/Cache.php',
  'Gila\\Controller'=> 'src/core/classes/Controller.php',
  'Gila\\Db'=> 'src/core/classes/Db.php',
  'Gila\\Event'=> 'src/core/classes/Event.php',
  'Gila\\FileManager'=> 'src/core/classes/FileManager.php',
  'Gila'=> 'src/core/classes/Config.php',
  'gForm'=> 'src/core/classes/Form.php',
  'gTable'=> 'src/core/classes/Table.php',
  'Gila\\Form'=> 'src/core/classes/Form.php',
  'Gila\\Table'=> 'src/core/classes/Table.php',
  'Gila\\TableSchema'=> 'src/core/classes/TableSchema.php',
  'Gila\\Image'=> 'src/core/classes/Image.php',
  'Gila\\Logger'=> 'src/core/classes/Logger.php',
  'Gila\\Menu'=> 'src/core/classes/Menu.php',
  'Gila\\Package'=> 'src/core/classes/Package.php',
  'Gila\\Router'=> 'src/core/classes/Router.php',
  'Gila\\Session'=> 'src/core/classes/Session.php',
  'Gila\\Slugify'=> 'src/core/classes/Slugify.php',
  'Gila\\Theme'=> 'src/core/classes/Theme.php',
  'Gila\\View'=> 'src/core/classes/View.php',
  'gpost'=> 'src/core/classes/HttpPost.php',
  'Gila\\HttpPost'=> 'src/core/classes/HttpPost.php',
  'Gila\\HtmlInput'=> 'src/core/classes/HtmlInput.php',
  'Gila\\User'=> 'src/core/models/User.php',
  'Gila\\Widget'=> 'src/core/models/Widget.php',
  'Gila\\Page'=> 'src/core/models/Page.php',
  'Gila\\Profile'=> 'src/core/models/Profile.php',
  'Gila\\Post'=> 'src/core/models/Post.php',
  'Gila\\Config'=> 'src/core/classes/Config.php',
];
