<div class="col-md-12">
    <h1 class="col-md-6"><?=$page_title?></h1>
    <div style="alignright">
        <a class="btn btn-primary">New Post</a>
    </div>
</div>

<?php
global $db;
$p_list = ['title', 'post', 'publish' ];
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $title = $_POST['p_title'];
    $text = $_POST['p_post'];
    $publish = $_POST['p_publish']?:0;
    $slugify = new Cocur\Slugify\Slugify();
    $slug = $slugify->slugify($title);
    $args = [$title,$text,$publish,$slug];
    if ($id == "new") {
        $db->query("INSERT INTO post(title,post,publish,slug) VALUES(?,?,?,?)",$args);
        $id = $db->insert_id;
    }
    else {
        $db->query("UPDATE post SET title=?,post=?,publish=?,slug=? WHERE id=$id",$args);
    }
    echo "<div class='alert success'>Changes have been saved successfully!</div>";
}
?>

<div class="col-md-12">
<form id="postForm" method="post" action="admin/posts/<?=($id?:'new')?>">
    <input value="<?=($id?:'new')?>" name="p_id" type="hidden"/>
    <div class="col-md-12">
        <label class="col-md-12">Title</label><br>
        <input value="<?=$title?>" name="p_title"/>
    </div>

    <div class="col-md-12">
        <label class="col-md-12">Text</label><br>
        <textarea name="p_post"><?=$text?></textarea>
    </div>

    <div class="col-md-12">
        <label><input type="checkbox" name="p_publish" value="1"<?=($publish=='1'?' checked':'')?>>Publish</label>
    </div>


    <div class="col-md-12">
        <label class="col-md-12">Meta Values</label><br>
        <input value="values here" />
    </div>

    <div class="col-md-12">
        <div class="btn-group">
            <a class="btn btn-primary" onclick="document.getElementById('postForm').submit()">Save</a>
            <a class="btn btn-default">Close</a>
        </div>
    </div>
</form>
</div>

<script src="libs/tinymce/js/tinymce/tinymce.min.js"></script>
<script>
//cdn.tinymce.com/4/tinymce.min.js
//tinymce.init({ selector:'textarea' });
tinymce.init({
  selector: 'textarea',
  mode: 'none',
  height: 300,
  theme: 'modern',
  plugins: [
    'advlist autolink lists link image bbcode imagetools charmap print preview hr anchor pagebreak',
    'searchreplace wordcount visualblocks visualchars code fullscreen',
    'insertdatetime media nonbreaking save table contextmenu directionality',
    'emoticons template paste textcolor colorpicker textpattern imagetools codesample toc example_dependency'
],
  toolbar1: 'save styleselect | forecolor backcolor bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link media image codesample',
  //theme_advanced_buttons3_add : "visualchars",
  //toolbar2: 'print preview  |   emoticons | ',
  image_advtab: true,
  templates: <?php echo json_encode($templates); ?>,
  document_base_url : "//localhost/gila/",
  content_css: <?php echo json_encode($content_css); ?>
    //'//localhost/gila/libs/bootstrap/bootstrap.min.css',
    //'//localhost/gila/libs/font-awesome/css/font-awesome.min.css',
    //'//localhost/gila/themes/bs-property/style.css',
    //'//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
    //'//www.tinymce.com/css/codepen.min.css'
 });

</script>
