<link href="lib/rj.css" rel="stylesheet">

<div class="col-3 gl-tt" data-tt="1st chart"><div></div></div>
<div class="col-3 gl-tt" data-tt="2nd chart"><div></div></div>
<div class="col-3 gl-tt" data-tt="3rd chart"><div></div></div>
<div class="col-3 gl-tt" data-tt="4th chart"><div></div></div>
<div class="col-3 gl-tt" tt="5th chart"><div></div></div>
<div class="col-3 gl-tt" tt="6th chart"><div></div></div>

<div id="gila-tooltip">Toolbox</div>

<script src="lib/rj.js"></script>
<script>
let gtt = document.getElementById('gila-tooltip')

function enableTips() {
    var elems = document.getElementsByClassName('gl-tt');
    for(var i = 0; i < elems.length; i++) {
        elems[i].addEventListener("mouseover", function(e){
			en = e.target
			while(en!=document) {
				if(en.hasAttribute('class')) if(en.classList.contains('gl-tt')) {
					gtt.style.visibility = 'visible'
					gtt.innerHTML = en.getAttribute('data-tt')
					gtt.style.left = (en.offsetLeft+en.offsetWidth/2)+'px';
					gtt.style.top = (en.offsetTop-5)+'px';
					console.log(en.getAttribute('data-tt'))
					return
				}
				en = en.parentNode
			}

			gtt.style.visibility = 'hidden'

		})

    }
}

data = [10, 15, 8, 22, 3, 12, 37, 17]
rj(".col-3 div").style('border-bottom','1px solid #999').createNS('svg',{width:200,height:200})

for(j=0; j<data.length; j++) {
	let i = j

	setTimeout(function () {
	rj(".col-3 div svg").createNS('rect',{
		x:10+i*20,
		width:20,
		'class':'trans-cubic-bezier',
		title:data[i],
		style:"fill:green;stroke-width:1;stroke:white;",
		height:0,
		y:200
	},{
		height:data[i]*5,
		y:200-data[i]*5
	})
	enableTips()

}, 100+i*100)


}


</script>

<?php
/*
require __DIR__ . '/vendor/autoload.php';

use Cocur\Slugify\Slugify;

$slugify = new Slugify();

echo $slugify->slugify('Hello World, this is a long sentence and I need to make a slug from it!');
*/
?>
